// 提取所有文本常量
export const TEXT = {
  NO_DATA: "暂无数据",
  NO_VIEW_SELECTED: "未选择视图",
  NO_SOURCES_ADDED: "请先添加新闻源到此视图",
  NO_SOURCE_DATA: "所选新闻源暂无数据",
  NO_SOURCES_TO_REFRESH: "此视图没有添加任何新闻源",
  LOADING: "正在加载数据...",
  CREATE_AGGREGATION: "新建聚合",
  NO_AGGREGATION_YET: "还没有创建聚合视图",
  CLICK_TO_CREATE_FIRST: "点击\"新建聚合\"创建您的第一个自定义聚合",
  SELECT_OR_CREATE_TITLE: "请选择或创建聚合视图",
  SELECT_OR_CREATE_DESC: "从左侧选择一个已有的聚合视图，或者创建一个新的聚合视图，将多个新闻源的内容组合在一起。",
  EDIT: "编辑",
  DELETE: "删除",
  REFRESH: "刷新",
  RETRY: "重试",
  SOURCES: "个新闻源",
  LOAD_FAILED: "加载失败",
  UNKNOWN_ERROR: "未知错误",
  LAST_UPDATE: "最后更新:",
  LOADING_TEXT: "加载中...",
  EXPAND_LIST: "展开聚合列表",
  COLLAPSE_LIST: "收起聚合列表",
  ALL_AGGREGATED_NEWS: "全部聚合新闻",
  REFRESHING_SOURCES: "正在刷新 {count} 个新闻源...",
  // 以下是从useAggregatedViewsMutation.ts提取的常量
  VIEW_CREATED: "聚合视图已创建",
  VIEW_UPDATED: "聚合视图已更新",
  VIEW_DELETED: "聚合视图已删除",
  CREATE_FAILED: "创建失败: ",
  UPDATE_FAILED: "更新失败: ",
  DELETE_FAILED: "删除失败: ",
  SERVER_NOT_CONFIGURED: "服务器配置不完整，无法同步数据。本地操作仍然有效。",
  SYNC_FAILED: "同步到服务器失败，但本地更改仍然保留",
  SERVER_ERROR: "服务器响应错误: ",
  // 新增刷新相关常量
  REFRESH_SUCCESS: "刷新成功，已获取最新数据",
  REFRESH_ERROR: "刷新失败，请稍后再试",
}
